version: "3.7"

services:
  strapi:
    image: ${BUILD_IMG}
    hostname: strapi
    container_name: strapi
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_SSL: ${DATABASE_SSL}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
    networks:
      - portfolio_network

networks:
  portfolio_network:
    external: true
