pipeline {
  agent any

  stages {
    stage('SCM Checkout') {
      steps {
        git branch: 'feature/jenkins', credentialsId: 'github-ssh', url: 'git@github.com:ajoel24/quiver.git'
      }
    }

    stage('Install dependencies') {
      steps {
        nodejs('my-nodejs') {
          sh "cd apps/next-frontend && npm install"
        }
      }
    }

    stage('SonarQube scan') {
      steps {
        script {
          def scannerHome = tool name: 'my-sonarqube', type: 'hudson.plugins.sonar.SonarRunnerInstallation';

          withSonarQubeEnv(credentialsId: 'sonarqube-token', installationName: 'my-sonarqube') {
            nodejs('my-nodejs') {
              sh "cd apps/next-frontend/ && ${scannerHome}/bin/sonar-scanner"
            }
          }
        }
      }
    }

    stage('Snyk scan') {
      steps {
        snykSecurity projectName: 'Next.js App', snykInstallation: 'my-snyk', snykTokenId: 'snyk-api-token', targetFile: 'logs.log'

        sh "cd apps/next-frontend/ && ${snykSecurity} monitor"
      }
    }
  }
}